### ISSUE TITLE
bad

### ISSUE THREAD

**Issue by Slab1337** [MoonDev1337/Moon#2]
poorly written lol

**Comment by relative** [comment]
unfortunately +1

**Comment by MoonDev1337** [comment]
> poorly written lol

well this is true, there isnt much i can do about it tho + its just an "example". python is slow so if i were to write an actual spammer i would choose to do it in c#.

another thing unrelated to this is, that you should stfu slab. you are a 20 year old "developer" that struggles with variables in python and sells a discord bot that can ping ips. with that said i hope you guys enjoy your weekend ill leave this problem open so people can see what kind of guy you are slab <3. another thing i might mention is that i wrote this while having to deal with alot of exams in school -> wich leads to not having alot of time. it does function so i see no reason to complain.


Slab go sell your discord ping bot and struggle with your say commands and dont piss off other people for no reason. you are 20 years old get a job and stop looking at discord spammers.

**Comment by Slab1337** [comment]
> 
> 
> > poorly written lol
> 
> well this is true, there isnt much i can do about it tho + its just an "example". python is slow so if i were to write an actual spammer i would choose to do it in c#.
> 
> another thing unrelated to this is, that you should stfu slab. you are a 20 year old "developer" that struggles with variables in python and sells a discord bot that can ping ips. with that said i hope you guys enjoy your weekend ill leave this problem open so people can see what kind of guy you are slab <3. another thing i might mention is that i wrote this while having to deal with alot of exams in school -> wich leads to not having alot of time. it does function so i see no reason to complain.
> 
> Slab go sell your discord ping bot and struggle with your say commands and dont piss off other people for no reason. you are 20 years old get a job and stop looking at discord spammers.

im 13

**Comment by relative** [comment]
he's lying

**Comment by relative** [comment]
he is 32

**Comment by Slab1337** [comment]
> it does function so i see no reason to complain.
dude its fucking not barely even working bro like atleest make it asynchronous retard

**Comment by MoonDev1337** [comment]
> > it does function so i see no reason to complain.
> > dude its fucking not barely even working bro like atleest make it asynchronous retard

it is also, no why would i. wouldnt speak like that considering me and khrysus and carl saw you struggle with say commands 

yikes.

like i said: "another thing i might mention is that i wrote this while having to deal with alot of exams in school -> wich leads to not having alot of time. "

next time you have a complaint comment without your "backup"

**Comment by MoonDev1337** [comment]
> > it does function so i see no reason to complain.
> > dude its fucking not barely even working bro like atleest make it asynchronous retard

also you sell a discord "networking" bot that pings ips for 5$. 

yikes

**Comment by Slab1337** [comment]
false information...

**Comment by relative** [comment]
not false

**Comment by Slab1337** [comment]
false

**Comment by MoonDev1337** [comment]
> false information...

https://youtu.be/KdwcQTJmi1U no i dont think it is

**Comment by relative** [comment]
> "backup"

I'm not his backup, I dislike both of you equally.

**Comment by Slab1337** [comment]
> like i said: "another thing i might mention is that i wrote this while having to deal with alot of exams in school -> wich leads to not having alot of time. "

that changes nothing

**Comment by MoonDev1337** [comment]
> > like i said: "another thing i might mention is that i wrote this while having to deal with alot of exams in school -> wich leads to not having alot of time. "
> 
> that changes nothing

would u mind not replying since i have other stuff todo. also ok it is poorly written idc.

i mentioned above tho why and other shit read it.

go sell your discord bot have a good day

**Comment by MoonDev1337** [comment]
> > "backup"
> 
> I'm not his backup, I dislike both of you equally.

thats nice. goodbye now tho

**Comment by relative** [comment]
No this is fun participating in this childish drama

**Comment by MoonDev1337** [comment]
> No this is fun participating in this childish drama

yes. i was kinda done now tho. <3
